name: Multi-Region EKS Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [us-east-1, eu-central-1, ap-southeast-1]

    env:
      TF_VAR_region: ${{ matrix.region }}
      AWS_REGION: ${{ matrix.region }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/GitHubTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=regions/${{ matrix.region }} init

      - name: Terraform Apply
        run: terraform -chdir=regions/${{ matrix.region }} apply -auto-approve
